apiVersion: apps/v1
kind: Deployment
metadata:
  name: java_back
  labels:
    app: java_back
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java_back
  template:
    metadata:
      labels:
        app: java_back
    spec:
      containers:
        - name: java_back
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "{{ .Values.env.POSTGRES_HOST }}"
            - name: POSTGRES_DB
              value: "{{ .Values.env.POSTGRES_DB }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-credentials
                  key: SPRING_DATASOURCE_PASSWORD