replicaCount: 1

image:
  repository: "749000351410.dkr.ecr.us-east-1.amazonaws.com/back_java"
  tag: "20251123211429" # Dica do Fabiano na primeira entrevista, deixar latest para não conflitar na edição do Git.
  pullPolicy: IfNotPresent

service: # Melhor estratégia para expor o serviço? Certificação AWS...
  type: ClusterIP
  port: 8080
  targetPort: 8080
