# Microsserviço
name: Deploy do Microsserviço 2

on:
#  push:            # Se execução automática
#    branches:
#      - main
#    paths:
#      - 'service2/**'
  workflow_dispatch: # Habilitando apenas execução manual.

# Configurações da AWS
permissions:
  id-token: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read
        
jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest # SO
      
# Validação manual se Repo AWS (ECR) existe (pode ou não ser criado uma única vez com a Infra)    
      env:
          ECR_REGISTRY: "749000351410.dkr.ecr.us-east-1.amazonaws.com" #${{ secrets.URL_AWS }}
          ECR_REPOSITORY: "microsservice2" #${{ secrets.REPO_NAME }}
          
      steps:
        - name: Checkout
          uses: actions/checkout@v4

# Clonar Repo Git no ambiente de execução da pipe.
        
        - name: Set IMAGE_TAG with current timestamp
          id: set_image_tag
          run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4 #uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume:  "arn:aws:iam::749000351410:role/github-carina-devops-pipe"
            aws-region: "us-east-1"
                  
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

# Criação do ECR
        - name: Create ECR repository if it doesn't exist
          run: |
            aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
            aws ecr create-repository --repository-name $ECR_REPOSITORY

# Construção da Imagem
        - name: Push to Amazon ECR
          run: |
            docker build -t $ECR_REPOSITORY:${{ env.IMAGE_TAG }} ./service2
            docker tag $ECR_REPOSITORY:${{ env.IMAGE_TAG }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}

# Repo que será a base para o Argo
        - name: Update helm values
          run: |
            sed -i "s/\(tag: \)\".*\"/\1\"${{ env.IMAGE_TAG }}\"/" charts/service2/values.yaml
            cat charts/service2/values.yaml

# Comitando e enviando a imagem para o repositório
        - name: Commit and push changes
          run: |
            git config user.email "devops79@yahoo.com"
            git config user.name "carina-pereira-devops"
            git add charts/service2/values.yaml
            if git diff --staged --quiet; then
              echo "Nenhuma alteração para commitar"
            else git commit -m "Atualiza tag image service2 para ${{ env.IMAGE_TAG }} [skip ci]"
              git push
            fi

              			  			